const fs = require("fs");
const path = require("path");

const root = path.resolve(__dirname, "..");
const jobs = {
  "v9-onN7EsWo": {
    3: "Does starting hospice mean I will die sooner?",
    6: "The short answer is no.",
    7: "Hospice does not cause a patient to die sooner.",
    12: "hospice can avoid unnecessary tests and respond quickly based on",
    13: "the patient's illness and related symptoms.",
    17: "This can also help the patient live longer,",
    19: "Good medication management in hospice can improve both the length",
    20: "and quality of a patient's life.",
    25: "Hospice does not simply stop all medications.",
    30: "Dementia medications do not cure dementia.",
    31: "They may slow its progression, but when dementia has reached",
    32: "the terminal stage, the expected benefit may no longer outweigh the burden.",
    41: "Blood pressure, diabetes, and cholesterol medicines also require care.",
    44: "That advice applies while the patient is in a stable condition.",
    50: "Family members may feel responsible for giving every medicine,",
    57: "Cholesterol medicine lowers cholesterol,",
    58: "but it may offer little benefit when a patient can no longer eat.",
    60: "These are general examples; every patient's needs are different.",
    76: "Now I would like to discuss morphine.",
    77: "Some families have a very strong reaction to the idea of morphine.",
    79: "It is a medication that must be used carefully.",
    83: "Shortness of breath may occur near the end of life.",
    85: "A pre-existing heart or lung condition can also worsen breathing",
    86: "during the terminal stage.",
    92: "The other common reason for morphine is severe pain.",
    93: "For cancer pain, clinicians may begin with a milder opioid",
    94: "and use morphine later if needed.",
    97: "Sublingual morphine is absorbed through blood vessels under the tongue",
    98: "and is given in very small amounts.",
    100: "Morphine is used to relieve shortness of breath and pain",
    101: "so the dying process is more comfortable, not to shorten it.",
    102: "We always discuss morphine with the family before starting it.",
    103: "Some families worry that it could hasten death.",
    108: "Many Korean families picture morphine as an injection.",
    109: "Most U.S. hospices use concentrated liquid morphine near the end of life.",
    110: "It is given under the tongue with a small syringe or dropper.",
    112: "A typical initial dose may be 0.25 to 0.5 mL, as prescribed.",
    117: "the dose or frequency can be adjusted gradually.",
    122: "A small number of people experience unwanted effects,",
    123: "such as confusion, hallucinations, or excessive sedation.",
    128: "In an extreme example, morphine was given when death seemed near,",
    129: "but relief of pain and distress helped the patient become alert and comfortable.",
    134: "Morphine is not needed by every patient.",
    135: "A person who dies peacefully in sleep may never need it.",
    138: "If breathing is gentle and there is no pain, morphine may not be needed.",
    144: "Medication labels may be written only in English,",
    162: "Medicines can save lives, but incorrect use can also cause serious harm.",
  },
  "XeGjlf7fILA": {
    1: "Today I will answer a common question from families:",
    2: "what happens after a patient dies?",
    8: "Hospice enrollment means a physician has certified a terminal illness",
    9: "and the patient and family have chosen comfort-focused care.",
    11: "The family has agreed to care at the patient's current location.",
    12: "When a hospice patient dies,",
    14: "the family should call the hospice office immediately.",
    15: "A hospice nurse will visit and pronounce the death.",
    17: "the hospice office calls the selected funeral home",
    18: "and arranges transportation of the deceased.",
    19: "Some families ask to wait a few hours before the transfer",
    20: "so they can spend time with the deceased",
    25: "The hospice will try to accommodate the family within legal limits.",
    29: "the deceased is transferred to the funeral home.",
    35: "you do not call 911; call the hospice office instead.",
    36: "Korean-operated funeral homes often arrive within about two hours.",
    38: "Other funeral homes may take up to about four hours.",
    40: "The process differs when the patient dies in a nursing facility.",
    41: "Because nurses are already present at the facility,",
    42: "a facility nurse may pronounce the death.",
    43: "The facility then calls the hospice company.",
    44: "Hospice contacts the funeral home selected by the family.",
    45: "If the patient dies at a nursing facility or at home,",
    46: "there may be no hospice clinician present at that moment.",
    47: "The family should call the hospice office,",
    48: "and a hospice nurse will come to pronounce the death.",
    55: "the funeral director sends the hospice a death worksheet.",
    56: "The worksheet contains information needed for the death certificate:",
    61: "The funeral director submits the information to the state.",
    62: "The state sends a physician attestation to the hospice office",
    63: "for the physician to certify the cause of death.",
    64: "After the physician signs the attestation,",
    65: "it is returned to the state for final verification.",
    66: "The state then issues the death certificate to the funeral home.",
    67: "Once the required documents are complete, the funeral home can proceed",
    68: "with the service, cremation, or burial.",
    70: "In short, the funeral home initiates the death-certificate process",
    71: "and receives the completed certificate.",
    80: "deceased and discuss funeral arrangements.",
    86: "In Korean, this role is similar to a spiritual-care counselor.",
    95: "After that, hospice begins bereavement services.",
    97: "This means support for the bereaved family.",
    98: "Hospice sends supportive information to the family",
    99: "for approximately one year after the death.",
    105: "Topics may include expected changes during grief and words of comfort.",
    123: "It cannot be avoided. Hospice helps make the final stage of life",
    124: "more meaningful and comfortable.",
    126: "Today I explained what happens after a hospice patient dies.",
    127: "Next time, I will explain the procedures when someone dies",
    128: "without receiving hospice care.",
  },
  "SNGsCjicC8E": {
    1: "In the last video, I explained what happens after a patient dies",
    2: "while receiving hospice care.",
    4: "Today I will explain the procedures when a patient dies",
    5: "without receiving hospice care.",
    6: "First, if a patient dies in a hospital while receiving treatment,",
    7: "medical staff pronounce the death and contact the funeral home.",
    8: "The funeral home then transfers the deceased from the hospital.",
    13: "It documents the level of medical treatment the patient wants",
    14: "in a life-threatening emergency.",
    15: "One common form is the POLST:",
    16: "Physician Orders for Life-Sustaining Treatment.",
    18: "It is a physician's medical order based on the patient's wishes.",
    19: "Usually printed on bright pink paper, it states whether CPR should be attempted",
    20: "if the patient's heart or breathing stops.",
    21: "If the POLST calls for attempted resuscitation,",
    22: "staff call 911 while beginning CPR",
    23: "and arrange transport to the hospital.",
    25: "If CPR is requested, the order will indicate",
    26: "Attempt Resuscitation/CPR.",
    27: "Staff must call 911, begin CPR,",
    28: "and send the patient to the hospital.",
    29: "CPR does not mean only chest compressions.",
    31: "Depending on the situation, it can include",
    32: "defibrillation, intubation, and other resuscitation measures.",
    34: "If the order is DNR, or Do Not Resuscitate,",
    35: "CPR is not performed.",
    38: "If there is no DNR order,",
    39: "staff begin CPR and emergency responders",
    40: "take all appropriate measures to try to resuscitate the patient.",
    43: "Paramedics will respond, and fire or police personnel may also come.",
    47: "The closest available emergency unit responds first.",
    55: "If the death appears suspicious, police contact the County Coroner.",
    56: "The coroner decides whether the body must be taken for examination",
    57: "and whether an autopsy is needed.",
    58: "",
    59: "",
    60: "",
    61: "The final situation is a death at home or in a nursing facility",
    62: "when the patient is not enrolled in hospice.",
    63: "Someone present should call 911.",
    64: "Paramedics, firefighters, or police will respond.",
    66: "Hospitals and many nursing facilities have clinicians who can pronounce death,",
    67: "but private homes generally do not.",
    70: "Responders check for a DNR order. Without one,",
    71: "they must attempt resuscitation.",
    73: "If the person dies, responders pronounce the death",
    74: "and police determine whether it appears natural or suspicious.",
    80: "Hospice is sometimes recommended for eligible patients at home",
    81: "to avoid this difficult emergency process after an expected death.",
    82: "Without hospice, the attending physician generally helps provide",
    83: "the information needed for the death certificate.",
    84: "Now I will say a little more about funeral homes.",
    86: "many Korean families in Orange and Los Angeles Counties use Korean funeral homes.",
    93: "Many families prefer them because they communicate in Korean",
    94: "and understand Korean funeral customs.",
    101: "Some funeral homes are located together with a cemetery",
    102: "and can provide both funeral and burial services.",
    105: "Funeral costs vary by provider.",
    109: "Direct cremation is another option.",
    110: "Both Korean-operated and other cremation providers are available,",
    111: "and prices vary.",
    117: "So far, I have explained the general procedures after death.",
    120: "Korean culture often avoids discussing death",
    121: "and may view the topic as ominous.",
    124: "I have come to believe that dying well is the completion of living well.",
    125: "Watching people near death has taught me humility,",
    126: "and reminds me to live this one life meaningfully.",
    129: "I will return with the question, \"Does hospice make you die sooner?\"",
  },
};

function srtTime(value) {
  let ms = Math.round(Math.max(0, value) * 1000);
  const h = Math.floor(ms / 3600000); ms %= 3600000;
  const m = Math.floor(ms / 60000); ms %= 60000;
  const s = Math.floor(ms / 1000); ms %= 1000;
  return `${String(h).padStart(2, "0")}:${String(m).padStart(2, "0")}:${String(s).padStart(2, "0")},${String(ms).padStart(3, "0")}`;
}

for (const [id, corrections] of Object.entries(jobs)) {
  const dir = path.join(root, "deliverables", `korean-video-${id}`);
  const jsonFile = fs.readdirSync(dir).find((name) => name.endsWith("_english_translation.json"));
  const base = jsonFile.replace("_english_translation.json", "");
  const items = JSON.parse(fs.readFileSync(path.join(dir, jsonFile), "utf8"));
  for (const [index, text] of Object.entries(corrections)) items[Number(index)].text = text;
  const clean = items.filter((item) => item.text.trim());
  fs.writeFileSync(path.join(dir, jsonFile), JSON.stringify(clean, null, 2) + "\n");
  fs.writeFileSync(path.join(dir, `${base}_english_translation.txt`),
    clean.map((x) => `[${srtTime(x.start)} --> ${srtTime(x.end)}] ${x.text}`).join("\n") + "\n");
  fs.writeFileSync(path.join(dir, `${base}_english_source.srt`),
    clean.map((x, i) => `${i + 1}\n${srtTime(x.start)} --> ${srtTime(x.end)}\n${x.text}`).join("\n\n") + "\n");
  console.log(`${id}: polished ${Object.keys(corrections).length} passages`);
}
